// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowTests.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CreateEmployee", Description="\tIn order to add employee\r\n\tAs a client app\r\n\tI want to be able to send create re" +
        "quest", SourceFile="Feature\\CreateEmployee.feature", SourceLine=0)]
    public partial class CreateEmployeeFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "CreateEmployee.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateEmployee", "\tIn order to add employee\r\n\tAs a client app\r\n\tI want to be able to send create re" +
                    "quest", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void CreateEmployeeWithValidDataInput(string name, string salary, string age, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ValidScenario"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create Employee with valid data input", null, @__tags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("I have entered {0} as a name of employee", name), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And(string.Format("I have entered {0} as salary", salary), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And(string.Format("I have entered {0} as  age", age), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
 testRunner.And("Request is prepared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
 testRunner.When("Request is sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 13
 testRunner.Then(string.Format("Guest should be created with data - {0},{1},{2}", name, salary, age), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 0", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant0()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Mateusz", "30000", "23", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 1", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant1()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Mateusz Wojtas", "0", "100", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 2", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant2()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Name", "1", "0", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 3", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant3()
        {
#line 7
this.CreateEmployeeWithValidDataInput("null", "30000", "23", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 4", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant4()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Mateusz", "null", "10", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 5", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant5()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Mateusz", "30", "null", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 6", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant6()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Mateusz", "-30", "10", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Create Employee with valid data input, Variant 7", new string[] {
                "ValidScenario"}, SourceLine=16)]
        public virtual void CreateEmployeeWithValidDataInput_Variant7()
        {
#line 7
this.CreateEmployeeWithValidDataInput("Mateusz", "30", "-10", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
